# NAME: Austin Zhang
# EMAIL: aus.zhang@gmail.com
#ID: 604736503

default:
	gcc -o lab1a -g -Wall -Wextra lab1a.c

clean: 
	rm -f lab1a lab1a-604736503.tar.gz

dist: 
	tar -cvzf lab1a-604736503.tar.gz lab1a.c README Makefile