# NAME: Austin Zhang
# EMAIL: aus.zhang@gmail.com
# ID: 604736503

default: 
	rm -f lab3b
	ln lab3b_ln lab3b
	chmod u+x lab3b

clean:
	rm -f lab3b-604736503.tar.gz lab3b

dist:
	tar -czvf lab3b-604736503.tar.gz lab3b.py lab3b_ln Makefile README