# NAME: Austin Zhang
# EMAIL: aus.zhang@gmail.com
# ID: 604736503

default:
	gcc -o lab3a -g -Wall -Wextra lab3a.c

dist:
	tar -czvf lab3a-604736503.tar.gz lab3a.c ext2_fs.h README Makefile

clean:
	rm -f lab3a lab3a-604736503.tar.gz 