# NAME: Austin Zhang
# EMAIL: aus.zhang@gmail.com
# ID: 604736503

default:
	tar -cvzf lab4a-604736503.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

clean:
	rm -f lab4a-604736503.tar.gz

dist:
	tar -cvzf lab4a-604736503.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README