# NAME: Austin Zhang
# EMAIL: aus.zhang@gmail.com
# ID: 604736503

default: 
	gcc -o lab0 -g -Wall -Wextra lab0.c
check: 
	~/Desktop/CS111/P0/smoke_test.sh
clean: 
	rm -f lab0 lab0-604736503.tar.gz
dist:
	tar -cvzf lab0-604736503.tar.gz lab0.c README Makefile backtrace.png breakpoint.png test0 smoke_test.sh